version: '2'
services:
  web:
    build: .
    ports:
      - "80:5000"
    volumes:
      - /opt/zerotribe:/opt/zerotribe
    links:
      - db:mongodb
    container_name: zerotribe_web_1
  db:
    image: mongo:3.0.2
